### ISSUE TITLE
Dragged node position after map padding

### ISSUE THREAD

**Issue by gharlock** [aleksplus/cytoscape-leaflet#1]
Hello,

a cytoscape node dragged *after* padding the map is placed in a wrong position.

The error seems proportional to the map padding.

**Comment by aleksplus** [comment]
Hello @gharlock, thanks for the bug report. Indeed was an issue with node dragging because i misused api methods aleksplus/cytoscape-leaflet@5420a80a61513ce6fb1f965b5efc2a18711e12a7.

new version is uploaded to npm 1.0.2, demo page should also work.
